### PR TITLE
Add empty dummy constructors

### PR DESCRIPTION
**Pull request by gerrygralton**
I'd appreciate the ability to have dummy constructors so that TCA9555 objects can be fields in other objects. There may be a better way to do this and I'm very open to suggestions. 
Cheers!

### CODE REVIEW

**Comment by RobTillaart** [comment]
Thanks for the PR,

With the "dummy" constructor the class variables do not get initialized. 
This may cause problems if people are going to use it in another way than you intend.
So it need a proper description in the readme.md file.

Can you add a small example sketch that uses the construct you have in mind?

**Comment by gerrygralton** [comment]
Thanks for having a look at this, Rob. Yes, an object initialised like this won't have the full functionalities of the class but this seems like the best way to get around the compiler telling me that they can't be a field in a separate class. Hopefully those changes make it more palatable!

**Comment by RobTillaart** [comment]
How about using a pointer to an TCA9555 in your object?
This is how dependency injection often is implemented.

```cpp
//    FILE: demo.ino
//  AUTHOR: Rob Tillaart
// VERSION: 0.1.0
//    DATE: 2023-08-10
// PURPOSE: demo

#include "Arduino.h"
#include "TCA9555.h"

TCA9555 TCA(0x27);

class Object
{
  TCA9555 *TCA;

  public:
  Object ( TCA9555 *param )
  {
    TCA = param;
  }

  int getType()
  {
    return TCA->getType();
  }
};

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);
  
  Object obj = Object( &TCA );
  Serial.println(obj.getType());
}

void loop() {

}

// -- END OF FILE --
```

**Comment by RobTillaart** [comment]
build failed but that is easy to fix => the variable obj seems to be reserved name or so.

**Comment by gerrygralton** [comment]
Thank you, that's a far more elegant solution! I'm going to close this PR as unnecessary. Thanks for your help!

**Comment by RobTillaart** [comment]
You're welcome!

**Pull request closed without merging**
